encoding: utf-8
language: en-us

# Site Settings
title: Favicon Valley Podcast
domain: faviconvalley.show
author:
  name: Brandon Brown
  email: hello@faviconvalley.show
description: > # ignore newlines in this value
  A podcast exploring products, email, and the web hosted by Brandon Brown.
meta_description: Exploring products, email, and the web.

# Favicons
favicon:
  ico: /favicon.ico
  png: /favicon.png
  theme_color: '#222222'

logo_url: https://d1a5a04sfj6djm.cloudfront.net/avatar256.png

# Routes
baseurl: '' # Use if your site is in a subdirectory, e.g. /blog/
root: /
permalink: /:title

assets_images: /assets/images
assets_scripts: /assets/scripts
assets_styles: /assets/styles

# Episodes RSS feed
episodes_rss_feed: http://simplecast.com/podcasts/1442/rss
itunes_url: https://itunes.apple.com/ca/podcast/favicon-valley/id1051186842

# Writing
markdown: redcarpet

# Build-stuff
keep_files: [
  'assets']

# Pagination
# paginate: 5
# paginate_path: /page/:num

defaults:
  -
    scope:
      path: ''
      type: episodes
    values:
      layout: episode
  # -
  #   scope:
  #     path: ''
  #     type: posts
  #   values:
  #     layout: post

collections:
  episodes:
    output: true
    permalink: /episodes/:title

# 3rd-party
social:
  twitter: faviconvalley
  github: faviconvalley

disqus:
  shortname: faviconvalley

google_analytics:
  id: UA-68371901-1
  domain: faviconvalley.show

# Extras
gems:
  - jekyll-sitemap
