# Routes
url: http://faviconvalley.show
assets_images: https://d1a5a04sfj6djm.cloudfront.net

debug: false

# Publishing
future: false
show_drafts: false

exclude: [
  '.ruby-version',
  '.editorconfig',
  'README.md',
  'Gulpfile.js',
  'package.json',
  'coffeelint.json',
  'Gemfile',
  'Gemfile.lock',
  'gulp',
  'node_modules',
  'build_dev']
