# Routes
url: http://127.0.0.1:8888

# Publishing
show_drafts: true

# Disable some things for development
google_analytics:
  id: ''
  domain: ''

disqus:
  shortname: ''

# Build settings
exclude: [
  '.ruby-version',
  '.editorconfig',
  'README.md',
  'Gulpfile.js',
  'package.json',
  'package-lock.json',
  'Gemfile',
  'Gemfile.lock',
  'gulp_tasks',
  'node_modules',
  'build_prod']
